micronaut:
  application:
    name: prova-estapar
  server:
    port: 3003
  router:
    static-resources:
      swagger:
        paths: "classpath:META-INF/swagger"
        mapping: "/swagger/**"
      swagger-ui:
        paths: "classpath:META-INF/swagger/views/swagger-ui"
        mapping: "/swagger-ui/**"
  openapi:
    enabled: true

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:postgresql://postgres:5432/estapar
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    schema-generate: UPDATE
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

garage:
  simulator:
    url: http://garage-simulator:3001

logger:
  levels:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.micronaut.data: TRACE